id: A79F4A4AE
title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
  of the Land of Snow'
type: translation
pechas:
- IEC43C38D
- I526802E8
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:59:23.949393
  last_modified_at: 2023-01-04 12:59:23.949416
  collections:
  - Longchen Rabjam Series
  - Works of Tibetan Masters
alignment_to_base:
  IEC43C38D/42A9: 3EBF
  I526802E8/8709: 3EBF
